version: "3.9"
services:
  postgres:
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DATABASE: ${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - pgsql:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d/
    networks:
      - network
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - network
    ports:
      - "8080:8080"
      - "9999:9999"
    restart: always
volumes:
  pgsql:
    driver: local
networks:
  network:
    driver: bridge