services:
  postgres:
    image: postgis/postgis:17-3.5
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DATABASE: ${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - pgsql:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d/
    networks:
      - network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DATABASE} -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 10s
      retries: 15
      start_period: 80s
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - network
    ports:
      - "8080:8080"
      - "9999:9999"
    restart: always
volumes:
  pgsql:
    driver: local
networks:
  network:
    driver: bridge